### PR TITLE
To do list

### PR DESCRIPTION
**Pull request by Unleashedicon**
### A simple to-do list
These are the main features of my to-do list:
- add tasks
- Delete selected tasks
- Edit tasks
- use of local storage

### CODE REVIEW

**Review by topeogunleye — CHANGES_REQUESTED** [review]
Hi @Unleashedicon, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

Try-Again

> ## (Highlights) Good Points: 💪 
> * Good commit messages. :heavy_check_mark:
> * No linter errors. :heavy_check_mark:
> * Followed Github flow :heavy_check_mark:
> * Professional README file. :heavy_check_mark:
> * PR has a good title and summary :heavy_check_mark:

## Required Changes ♻️
- [ ] I kindly suggest that you should have an array of simple *to do tasks* (array of objects) with each object containing three keys - description \[`string`\], completed \[`bool`\], index: \[`number`\]:
image (2)


- [ ] This is your array below and it's currently empty.

image

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- [ ] kindly suggest that remove your `node_modules` folder from your `to-do-list` branch as you may have mistakenly pushed  `node_modules` to your branch repo. `node_modules/` has a large size and should be excluded from the remote repository

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by emmiiorji — CHANGES_REQUESTED** [review]
Hi @Unleashedicon, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

<div align='center'>

</div>

You have submitted the same pull request for multiple milestones. The task  **To Do list: add & remove** is required to be submitted in a new pull request.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by divinecharlotte — CHANGES_REQUESTED** [review]
Hi @Unleashedicon  , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight 💯 
- No linters errors ✔️ 
- clean code ✔️ 
- Descriptive PR ✔️ 

## Required Changes ♻️

- [ ] kindly consider adding a working link to your readme on the live demo section it will make your readme look more professional or consider removing it as you haven't yet deployed your project

_Check the comments under the review._



## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by KDlamini — CHANGES_REQUESTED** [review]
### Hi @Unleashedicon 🙋‍♀️,  

You have done an incredible job implementing some of the changes requested by the previous reviewer. 👏🏾👏🏾👏🏾  
However, there are still some changes that aren't addressed yet. You are almost there! 💪🏾 

## Highlights 🌞 

✔️ An array of tasks with properties tasks, completed, and index is implemented

## Required Changes ♻️

- As requested by the previous reviewer, kindly remove the `Live demo` section since your application is not deployed. You can restore the section should the project requirements instruct you to deploy your application. 

image

-  As requested by the previous reviewer, kindly remove the `node_modules` folder and make sure that it is correctly included in the `.gitignore` file. The node module folder contains a lot of files which increase the size of your repo and thus make your pull request very slow. You can delete the folder directly from GitHub.

image


Cheers 🥂  and Happy coding!!! 👯 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me @KDlamini in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Unleashedicon** [comment]
> ### Hi @Unleashedicon 🙋‍♀️,
> You have done an incredible job implementing some of the changes requested by the previous reviewer. 👏🏾👏🏾👏🏾 However, there are still some changes that aren't addressed yet. You are almost there! 💪🏾
> 
> ## Highlights 🌞
> ✔️ An array of tasks with properties tasks, completed, and index is implemented
> 
> ## Required Changes ♻️
> * As requested by the previous reviewer, kindly remove the `Live demo` section since your application is not deployed. You can restore the section should the project requirements instruct you to deploy your application.
> 
> image
> 
> * As requested by the previous reviewer, kindly remove the `node_modules` folder and make sure that it is correctly included in the `.gitignore` file. The node module folder contains a lot of files which increase the size of your repo and thus make your pull request very slow. You can delete the folder directly from GitHub.
> 
> image
> 
> Cheers 🥂 and Happy coding!!! 👯 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Remember to tag me @KDlamini in your question so I can receive the notification.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

### I Have deleted the node_ modules it is there because it is showing you the files changed but from the code itself there is no node_modules

**Review by amejid — APPROVED** [review]
Hi @Unleashedicon, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- Linter checks passing :heavy_check_mark: 
- Webpack successfully configured :heavy_check_mark: 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
